"""empty message

Revision ID: 1ba3af1d0c78
Revises: df8085a0b577
Create Date: 2016-07-14 15:33:15.887552

"""

# revision identifiers, used by Alembic.
revision = '1ba3af1d0c78'
down_revision = 'df8085a0b577'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    ### end Alembic commands ###
