"""empty message

Revision ID: d063873cc4cd
Revises: 1ba3af1d0c78
Create Date: 2016-07-18 12:09:00.902206

"""

# revision identifiers, used by Alembic.
revision = 'd063873cc4cd'
down_revision = '1ba3af1d0c78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_sku', sa.Column('price', sa.Float(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_sku', 'price')
    ### end Alembic commands ###
