"""empty message

Revision ID: df8085a0b577
Revises: 463f844de27b
Create Date: 2016-07-14 13:41:48.254847

"""

# revision identifiers, used by Alembic.
revision = 'df8085a0b577'
down_revision = '463f844de27b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('description', sa.String(length=500), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'description')
    ### end Alembic commands ###
